name: gtbook
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter-book=0.12.1
  - pip
  - python-graphviz
  - ipywidgets>=7.5
  - pandas
  - pip:
      - plotly # in pip for binder
      - gtbook
