name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
      - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Activate miniconda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          auto-activate-base: false
          activate-environment: gtbook
          environment-file: conda-linux-64.lock
          # python-version: 3.7
          # environment-file: environment.yml 
      - run: conda info --envs
      - run: conda list
      - run: pip install plotly==5.5.0
      - run: pip install gtbook
      
      - name: Build Frank and Seth's book
        run: |
          jupyter-book build .

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
