name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
      - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Activate miniconda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          auto-activate-base: false
          activate-environment: gtbook
          environment-file: environment.yml
        run: |
          jupyter-book build .

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
